### ISSUE TITLE
Compilation dependency error

### ISSUE THREAD

**Issue by Jamamuuga** [unavi-xyz/bevy_vrm#36]
Greetings, I'm making some supplementary 3D animated video for a project with an aggressive deadline using the bevy_vrm commit that adds Bevy 0.14 support. When I compile using bevy_vrm as a dependency it gives an error that bevy_vrm requires bevy_gltf_kun (which is getting pulled from its github repo) with features = "import" but bevy_gltf_kun doesn't have that feature. Somehow when I compile the VRM Viewer crate it doesn't trigger that issue... I checked the bevy_gltf_kun repo and couldn't find any reference to a feature called "import". Please advise etc, thx! :D

**Comment by Jamamuuga** [comment]
Btw, after I make a few videos, I plan to eventually roll my own VTubing app eventually for some activities. I plan to pipe in the tracking, for now, from another app using the vmc protocol! :D 👯

**Comment by Jamamuuga** [comment]
In the meantime I'm going to try to use a copy of that commit and setup workspaces & crate folders to replicate the method or similar that vrm_viewer workspace/example managed to use to bypass the non-present feature "import" issue of bevy_gltf_kun. Also, thank you so much for making such a critical plugin for the Bevy, VTubing, & 3D animated video communities! 👍

**Comment by Jamamuuga** [comment]
So far my best guess of how vrm_viewer managed to avoid the error is maybe the properties of either workspaces or Cargo.lock files, but I'm not a thorough enough expert on the deep details of those yet to know for sure... 🤔

**Comment by kayhhh** [comment]
ah yes, I have been doing some updates to bevy_gltf_kun and removed the "import" feature, so its now causing an error. I will hopefully finish the 0.14 upgrade today for bevy_gltf_kun (animations are currently broken) and put out a release so we can start depending on that rather than the github branch.

**Comment by kayhhh** [comment]
I just pushed a commit to bevy_vrm that should fix this for now

**Comment by Jamamuuga** [comment]
Thank you so much! :D I will try it later today so I can roll back some of the workaround stuff I was setting up. I'm so glad I set up workspaces though. I am likely to need to factor more stuff out into local Bevy plugins, later crates, & even later actually release some of my crates! It is so nice to be prepared for that trajectory sooner rather than later!... 😍
